### ISSUE TITLE
Can't get AngularJS's ngResource to work

### ISSUE THREAD

**Issue by MarceloBorgesP** [MarceloBorgesP/BeerOnlineMEAN#2]
When using this featuree, we are getting the following error:

![screenshot from 2015-11-13 09 17 20](https://cloud.githubusercontent.com/assets/4267241/11144921/bd58b126-89e7-11e5-9695-b576f7a2f89f.png)

It should be properly fixed in order to keep going with our project

**Comment by MarceloBorgesP** [comment]
Hey @edysegura, you are the Angular man, could you help me with this?

It says that "app is not defined", but as long as I know it's declared on my [routes file](https://github.com/MarceloBorgesP/BeerOnlineMEAN/blob/feature/ngResource/public/js/appRoutes.js) 

Just be aware that the error occurs on my "feature/ngResource" branch. I've created a new branch not to mess up the main project.

**Comment by edysegura** [comment]
Hi @MarceloBorgesP! When it says app is not defined it might be because the order you have include your JavaScript to page. Please check that!

Look at [this project](https://github.com/univas/fxos-factorial).

![image](https://cloud.githubusercontent.com/assets/5324414/11171611/9215314c-8bdb-11e5-9944-2d47c5790d05.png)

![image](https://cloud.githubusercontent.com/assets/5324414/11171605/78f69412-8bdb-11e5-94d9-232113a35dbc.png)

![image](https://cloud.githubusercontent.com/assets/5324414/11171628/fce803e6-8bdb-11e5-9efe-f335a054a42a.png)

![image](https://cloud.githubusercontent.com/assets/5324414/11171635/1bcbf7ae-8bdc-11e5-97c2-f09256fe0283.png)
